server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/server_sent_envent_product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect